name: CD - main branch

on:
  push:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        
    - name: Install dependencies
      run: cd ./express && npm ci

    - name: Copy dir to host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        rm: true
        source: './express'
        target: '~/github/foxbel-api'
        strip_components: 2
    
    - name: Execute deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        script: 'cd ~/github && sh deploy.sh foxbel-api'
